### ISSUE TITLE
[FEAT] www-Version vs. non-www version

### ISSUE THREAD

**Issue by manniL** [Musimaniac/IdleonCompanion#102]
**Which categories does your suggestion apply to?**
- [x] Other tools/misc

**Is your feature request related to a problem? Please describe.**
A good pratice is providing only one "version" of the site. Either with www in front or without.

**Describe the solution you'd like**
Migrate non-www to www or vice-versa. But be aware that localStorage is, at least right now, bound to the whole domain. This means, people could *lose* their progress (😢) unless a migration option (e.g. exporting as JSON object and importing again) is given.

**Comment by Musimaniac** [comment]
done ;)

no problem of loss of data, since no one was using the www version (broken, as you pointed out in the second issue). Migration option with cloud backup is completed and functional in a pr, if you want to check it out.
