### ISSUE TITLE
[FEAT] Add discord integration option

### ISSUE THREAD

**Issue by F1r3w477** [Musimaniac/IdleonCompanion#104]
**Which categories does your suggestion apply to?**
- [x] UI changes
- [x] Tracking
- [ ] Calculators
- [x] Other tools/misc

**Is your feature request related to a problem? Please describe.**
Can't sync data between devices, and data can get lost for no reason on the same device. Data can also get lost on clearing cookies and cache. 

**Describe the solution you'd like**
Allow users to authentic via discord to sign in to the website as a means of saving data across devices and allowing for better customization. 

**What data is needed for the suggestion?**
Discord username, you would need to set up a discord app. 
![image](https://user-images.githubusercontent.com/9701525/119240722-3c956e00-bb17-11eb-805f-4f678f51180a.png)

**Additional context**
I just think this would be a nice thing to add, as it would allow us to authenticate with discord so we can save our data to our discord account. This would allow access on multiple devices, and make sure our data isn't wiped on cookie clear or something. (My data just recently disappeared completely.) You could allow the user to change their main character icon to their discord profile picture or something. This also would allow for some fun integration into the ICD Public discord server.

**Comment by Musimaniac** [comment]
If you look into the recent PRs, there is already cloud saving integrated via Firebase. Google, Github and email accounts are supported
