### ISSUE TITLE
[FEAT] Allow downgrading of card levels in progress tracker

### ISSUE THREAD

**Issue by F1r3w477** [Musimaniac/IdleonCompanion#106]
**Which categories does your suggestion apply to?**
- [ ] UI changes
- [x] Tracking
- [ ] Calculators
- [ ] Other tools/misc

**Is your feature request related to a problem? Please describe.**
You need to click all the way through the card if you set the level too high 

**Describe the solution you'd like**
Let the user right-click the card to downgrade the level.

**What data is needed for the suggestion?**
Any required data is present in the current build.

**Additional context**
It works in the vials section of alchemy, so I assume it's pretty easy to implement.

**Comment by Musimaniac** [comment]
closing it as it's a duplicate issue, certainly doable
