### ISSUE TITLE
[FEAT] Tracking total money in the bank (stash)

### ISSUE THREAD

**Issue by F1r3w477** [Musimaniac/IdleonCompanion#109]
**Which categories does your suggestion apply to?**
- [x] UI changes
- [x] Tracking
- [ ] Calculators
- [ ] Other tools/misc

**Is your feature request related to a problem? Please describe.**
A lot of people like to store their money in the bank for all their characters to use. Some people would find it nice to be able to track how much they have. 

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/9701525/119250318-ee0ec080-bb64-11eb-9e36-94e6791de3bd.png)
Just show somewhere the total money in the bank the user has. You have a lot of open space on the character sheet, could throw it there.

**What data is needed for the suggestion?**
Nothing that isn't in the current build.

**Additional context**
<3

**Comment by Musimaniac** [comment]
it's a small thing, but I don't know really how useful it would be. My personal opinion (there could be disagreement) is that we shouldn't strive for fulll tracking of every little piece of data in the game. it would become cumbersome quickly, and in most cases it wouldn't add any functionality. 
f.ex in this case, you can check your total money in two clicks from everywhere in the game, what functionality could it add to keep a static variable on the website, that had to be constantly and manually updated?

**Comment by adapap** [comment]
Agree with @Musimaniac here. This is why I also consider tracking things like anvil production, guild points, consumables (like silver pens/talent reset points) and anything else that doesn't _directly_ contribute to some sort of useful calculation.
