### ISSUE TITLE
[FEAT] - move Alchemy vials

### ISSUE THREAD

**Issue by Teglhus** [Musimaniac/IdleonCompanion#131]
**Which categories does your suggestion apply to?**
- [x] UI changes
- [ ] Tracking
- [ ] Calculators
- [ ] Other tools/misc

**Describe the solution you'd like**
Move the Alchemy Vials to the top, as its quite hidden under the Alchemy upgrades (quite easy to never see it)

![image](https://user-images.githubusercontent.com/86340128/123042998-eeb2a500-d3f7-11eb-83b3-22ac59fa972c.png)

**Comment by Liulangzhe98** [comment]
I am currently working on redesigning the alchemy page completely, so it will also contain the costs for upgrading.
I was thinking of splitting the Alchemy page into multiple pages:
  1. Bubbles.  Split into the 4 different cauldrons
  2. Liquid + Vials + Pay2Win . These can also be split apart, but since they are all quite small I think it might be better to combine them on one page.

**Comment by Teglhus** [comment]
Sounds good. About pricing for upgrades, would this not be too difficult? There is quite some game mechanics that can affect the price for alchemy bubbles and vials.

**Comment by Liulangzhe98** [comment]
The price of vials is set in stone. About the bubbles, I think i got all formulas for this. I already had the formulas for this [sheet](https://docs.google.com/spreadsheets/d/1w7tJ3CMB7gmW2oPc3TBS0qjy8gzfIDFEHFxX8tGNr5E/edit?usp=sharing), so I only have to rewrite it to the website.

**Comment by Liulangzhe98** [comment]
Progress is being made. 
![image](https://user-images.githubusercontent.com/16001258/124141076-5d8f9e00-da89-11eb-9854-1b2669b7dc7f.png)

**Comment by Teglhus** [comment]
Looking great :)

**Comment by 3ICE** [comment]
Please make sure to also include what each bubble with roman numerals does.
Seeing plain I, II, and III, etc. are useless to me as I don't know what they do.
I need tooltip information like +6 AGI, +0.2% mastery, or 1% drop rate, etc.

**Comment by Liulangzhe98** [comment]
@3ICE Could you make a seperate Issues for this? Since this issue is more about the vials getting their own page and this issues can be closed since the rework is merged.

**Comment by 3ICE** [comment]
Done. #140
