### ISSUE TITLE
Version Check, LocalStorage Cleaning 

### ISSUE THREAD

**Issue by Musimaniac** [Musimaniac/IdleonCompanion#30]
At the moment the app deletes all previous data for each new version, but In the future we should offer a prompt for exporting data, and reimport in the correct format.

Thoughts?

**Comment by adapap** [comment]
Actually that's not what's happening. The idea is to store the version in localStorage such that we can programmatically update the saved data as it changes over time. See [Wikipedia](https://en.wikipedia.org/wiki/Version_control) explain version controlling.

For example, if the current data stored in local storage is v1.2 but the app is at v1.4, it can migrate the data automatically without loss of data. This requires strict management/changelogs to make sure versioning is consistent.

**Comment by Musimaniac** [comment]
perfect, you cleared my doubts. As a note, when we deploy we will have some local data, from the previous version of the website. 
Might be worth transitioning the checklist portion?

**Comment by adapap** [comment]
I'm not sure that it's going to be easy to port the data that's already stored since it tracks characters that aren't created yet, has different identifiers for the keys, etc. At the very least we can warn users that the data will be cleared but I don't know how I would write a migration for that data.

**Comment by Musimaniac** [comment]
yes fair. It the context of a one time occurrence it's not too bad. We just need to popup a little message explainign the reasons of the change. and the added functionality
