### ISSUE TITLE
Completion Indicators

### ISSUE THREAD

**Issue by adapap** [Musimaniac/IdleonCompanion#60]
Add some metrics that lets people quickly gauge how much progress a character has made. Ideas include completion in terms of items unlocked, tools equipped, or levels achieved. Some of these metrics should add more flavor to the character card so you can see that Character X has Y skill levels, Z% of bags, etc.

**Comment by Musimaniac** [comment]
could put a little icon on the char card corresponding to the highest leveled skill. It would show at a glance who's the best miner/logger/fisher[...]
Items completions is good, as a quick one number metric for inventory/bags collection. Skills, Main levels and statues can only be used relative to other characters in the account, Imho. 
f.ex: you can't say that a level 95 char is at 80% completion as an absolute, but we could say that it's x% of the highest leveled character in the account.
