### ISSUE TITLE
VueUse Global State

### ISSUE THREAD

**Issue by adapap** [Musimaniac/IdleonCompanion#73]
Improve the developer experience with saving/loading from localStorage using VueUse composable to bind data to a global state. This will let us simply assign values to different `ref` objects and not have to worry about saving/loading from the store. Default values are supported. We can potentially simplify our data into one or two objects and this library will take care of mutability.

https://vueuse.org/core/createglobalstate/

**Comment by Musimaniac** [comment]
That's a great idea. Is it something that we should take care of before going public?
