### ISSUE TITLE
Shared character data/state

### ISSUE THREAD

**Issue by adapap** [Musimaniac/IdleonCompanion#8]
Going forward, we should have all character-specific items tied to the character rather than whatever feature the data is being used in. For example, instead of nesting the character progress inside a feature (such as keeping track of which characters have which carry capacity pouch), the character will keep track of its individual progress. This makes it easy to manage/share characters as you can have stats, statues, bags/pouches, skill levels, etc. all be tied to the character.

**Quick Example**
Instead of:
`blunderbag0: false, blunderbag1: false, blunderbag2: false` or `blunderbag: [false, false, false]`
We store this as:
`chars[0].progress['blunderbag'] = false, ...` or similar

**Comment by Musimaniac** [comment]
yes, that's an excellent idea. That would open up opportunity in the future for more complex representation and manipulation of character data, and simplify existing features.
