### ISSUE TITLE
[BUG] Top Skill in character cards only compares first digit of inserted skills

### ISSUE THREAD

**Issue by Musimaniac** [Musimaniac/IdleonCompanion#92]
**What version of the website are you using?**
0.2

**Describe the bug**
The top skill display in the character cards only takes into account the first digit of skill values. A char with a fishing of 6 will retain top status over a char with fishing 20. Likewise, two chars with skills at 20 and 25 will be shown as equal

**Comment by adapap** [comment]
This one shouldn't be an issue for new users as it occurred before I enforced a numeric cast on the skill level input. You should be able to fix this by changing the level and then back for any remaining problematic skills.

**Comment by Teraphas** [comment]
issue still occurring when i change skill levels to remove the 0s i added before all single digit entries to make it work properly. my 8 on catching still ends up flagged as the highest leveled skill
