### ISSUE TITLE
[BUG] Active Squire Build is misleading

### ISSUE THREAD

**Issue by manniL** [Musimaniac/IdleonCompanion#94]
**What version of the website are you using?**
0.2

**Describe the bug**
The Tab 2 talents and description are contradictionary in the "Squire Active ~Lvl. 70" build.

Description:

> Go for 1 in each active skill, then you want to max "Carry A Big Stick", then mix "Absolute Unit" and "Strength in numbers". As you gain more levels, considering putting points in Whirl.

Image:

* 100 in Carry a Big stick ✔️ 
* 100 in Strength in Numbers ✔️ 
* 100 in Firmly Grasp it ❌ 
* 41 in Double Strike ❌ 

**Screenshots**
![grafik](https://user-images.githubusercontent.com/640208/117619993-45c62880-b170-11eb-9c09-c7ff34764904.png)

**Comment by Musimaniac** [comment]
probably a mistake when copying over from the toolbox, thanks for the report. A builds revision is expected sometime this week

**Comment by manniL** [comment]
It seems it is an issue in the Toolbox as well btw.
